list(APPEND CMAKE_MODULE_PATH ${SWIFT_CMAKE_MODULES_DIR} ${SWIFT_CMAKE_PROJECTS_DIR})

set(COMPILER_RT_ENABLE_IOS FALSE CACHE BOOL "")
set(COMPILER_RT_ENABLE_WATCHOS FALSE CACHE BOOL "")
set(COMPILER_RT_ENABLE_TVOS FALSE CACHE BOOL "")
