list(APPEND CMAKE_MODULE_PATH ${SWIFT_CMAKE_MODULES_DIR} ${SWIFT_CMAKE_PROJECTS_DIR} )

#include(HostSDK)
include(LLVMConfig)
include(ExternalProject)

ExternalProject_Add(
  llvm
  SOURCE_DIR "${CMAKE_SOURCE_DIR}/../llvm/"
  CMAKE_ARGS
    -DCMAKE_VERBOSE_MAKEFILE=1
    -DCMAKE_C_FLAGS=${LLVM_CMAKE_C_FLAGS}
    -DCMAKE_CXX_FLAGS=${LLVM_CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS_RELWITHDEBINFO=${LLVM_CMAKE_C_FLAGS_RELWITHDEBINFO}
    -DCMAKE_CXX_FLAGS_RELWITHDEBINFO=${LLVM_CMAKE_CXX_FLAGS_RELWITHDEBINFO}

    -DCMAKE_BUILD_TYPE:STRING=${LLVM_BUILD_TYPE}
    -DLLVM_ENABLE_ASSERTIONS=${LLVM_ENABLE_ASSERTIONS}
    -DLLVM_TARGETS_TO_BUILD=${LLVM_TARGETS_TO_BUILD}
    -DCLANG_VENDOR=Apple
    -DCLANG_VENDOR_UTI=com.apple.compilers.llvm.clang
    -DPACKAGE_VERSION=4.0.0
    -DLLVM_TOOL_SWIFT_BUILD:BOOL=${LLVM_TOOL_SWIFT_BUILD}
    -DLLVM_INCLUDE_DOCS:BOOL=${LLVM_INCLUDE_DOCS}
    -DLLVM_ENABLE_LTO:STRING=${LLVM_ENABLE_LTO}
    -DCMAKE_OSX_DEPLOYMENT_TARGET:STRING=${DARWIN_DEPLOYMENT_VERSION_OSX}
    -DCMAKE_OSX_SYSROOT:PATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
    -DLLVM_ENABLE_LIBCXX:BOOL=${LLVM_ENABLE_LIBCXX}
    -DCOMPILER_RT_ENABLE_IOS:BOOL=${COMPILER_RT_ENABLE_IOS}
    -DCOMPILER_RT_ENABLE_WATCHOS:BOOL=${COMPILER_RT_ENABLE_WATCHOS}
    -DCOMPILER_RT_ENABLE_TVOS:BOOL=${COMPILER_RT_ENABLE_TVOS}
    -DSANITIZER_MIN_OSX_VERSION=${DARWIN_DEPLOYMENT_VERSION_OSX}
    -DLLVM_ENABLE_MODULES:BOOL=${LLVM_ENABLE_MODULES}
    -DLLVM_TOOL_COMPILER_RT_BUILD:BOOL=${LLVM_TOOL_COMPILER_RT_BUILD}
    -DLLVM_BUILD_EXTERNAL_COMPILER_RT:BOOL=${LLVM_BUILD_EXTERNAL_COMPILER_RT}
    -DLLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING:BOOL=${LLVM_DISABLE_ABI_BREAKING_CHECKS_ENFORCING}
    -DLLVM_HOST_TRIPLE:STRING=x86_64-apple-macosx10.9
    -DLLVM_LIT_ARGS=${LLVM_LIT_ARGS}
    -DCMAKE_INSTALL_PREFIX:PATH=${LLVM_CMAKE_INSTALL_PREFIX}
    -DINTERNAL_INSTALL_PREFIX=${INTERNAL_INSTALL_PREFIX}
    
    -DCMAKE_LIBTOOL=/Users/erg/swiftenv4/libtool
    -DCMAKE_C_COMPILER=/Users/erg/swiftenv4/clang
    -DCMAKE_CXX_COMPILER=/Users/erg/swiftenv4/clang++
  INSTALL_COMMAND cmake -E echo "Skipping install step."
)
