list(APPEND CMAKE_MODULE_PATH ${SWIFT_CMAKE_MODULES_DIR} ${SWIFT_CMAKE_PROJECTS_DIR} ${SWIFT_CMAKE_SDKS_DIR})

set(SWIFT_STDLIB_BUILD_TYPE ${CMAKE_BUILD_TYPE} CACHE STRING "")
set(SWIFT_STDLIB_ASSERTIONS TRUE CACHE BOOL "") # TRUE if swift_optimized
set(SWIFT_STDLIB_ENABLE_RESILIENCE FALSE CACHE BOOL "")
set(SWIFT_STDLIB_SIL_SERIALIZE_ALL TRUE CACHE BOOL "")
set(SWIFT_STDLIB_SIL_DEBUGGING FALSE CACHE BOOL "") # BUILD_SIL_DEBUGGING_STDLIB
