message(STATUS "Included SwiftConfig.cmake")

set(SWIFT_VERSION "3.1" CACHE STRING
    "The user-visible version of the Swift compiler")
set(SWIFT_VENDOR "" CACHE STRING
    "The vendor name of the Swift compiler")
set(SWIFT_COMPILER_VERSION "" CACHE STRING
    "The internal version of the Swift compiler")
set(CLANG_COMPILER_VERSION "" CACHE STRING
    "The internal version of the Clang compiler")

# CMAKE_C_FLAGS
# CMAKE_CXX_FLAGS
set(CMAKE_C_FLAGS_RELWITHDEBINFO "-O2 -DNDEBUG" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -DNDEBUG" CACHE STRING "")
set(SWIFT_NATIVE_LLVM_TOOLS_PATH "" CACHE STRING "")
set(SWIFT_NATIVE_CLANG_TOOLS_PATH "" CACHE STRING "")
set(SWIFT_NATIVE_SWIFT_TOOLS_PATH "" CACHE STRING "")
set(SWIFT_ANALYZE_CODE_COVERAGE FALSE CACHE STRING "") # FALSE NOT-MERGED MERGED
set_property(CACHE SWIFT_ANALYZE_CODE_COVERAGE PROPERTY
    STRINGS "FALSE" "NOT-MERGED" "MERGED")

set(SWIFT_TOOLS_NUM_PARALLEL_LTO_LINK_JOBS "" CACHE STRING "")

set(SWIFT_INCLUDE_TESTS FALSE CACHE BOOL "")
set(SWIFT_INCLUDE_TOOLS FALSE CACHE BOOL "")
set(SWIFT_TOOLS_ENABLE_LTO "" CACHE STRING "") # OFF thin full

# ergomg
# When LTO is enabled, disable LLVM_ENABLE_MODULE_DEBUGGING
if(NOT ${SWIFT_TOOLS_ENABLE_LTO} STREQUAL "")
  set(LLVM_ENABLE_MODULE_DEBUGGING FALSE)
  set(SWIFT_ENABLE_MODULE_DEBUGGING FALSE)
  set(SWIFT_PARALLEL_LINK_JOBS ${SWIFT_TOOLS_NUM_PARALLEL_LTO_LINK_JOBS})
endif()


set(SWIFT_SERIALIZE_STDLIB_UNITTEST FALSE CACHE BOOL "")

set(SWIFT_BUILD_REMOTE_MIRROR FALSE CACHE BOOL "")
set(SWIFT_BUILD_DYNAMIC_STDLIB FALSE CACHE BOOL "")
set(SWIFT_BUILD_STATIC_STDLIB FALSE CACHE BOOL "")
set(SWIFT_BUILD_DYNAMIC_SDK_OVERLAY FALSE CACHE BOOL "")
set(SWIFT_BUILD_STATIC_SDK_OVERLAY FALSE CACHE BOOL "")
set(SWIFT_BUILD_PERF_TESTSUITE FALSE CACHE BOOL "")
set(SWIFT_BUILD_EXAMPLES FALSE CACHE BOOL "")
set(SWIFT_BUILD_RUNTIME_WITH_HOST_COMPILER FALSE CACHE BOOL "")
set(SWIFT_CHECK_INCREMENTAL_COMPILATION FALSE CACHE BOOL "")

set(SWIFT_INSTALL_COMPONENTS "" CACHE STRING "")
set(SWIFT_EMBED_BITCODE_SECTION FALSE CACHE BOOL "")

set(SWIFT_BENCHMARK_NUM_O_ITERATIONS "3" CACHE STRING "")
set(SWIFT_BENCHMARK_NUM_ONONE_ITERATIONS "3" CACHE STRING "") # or 20 ergomg

set(SWIFT_DARWIN_XCRUN_TOOLCHAIN "XcodeDefault" CACHE STRING "")

function(print_swift_config)
  message(STATUS "SwiftConfig Begin")
  message(STATUS "CMAKE_C_FLAGS_RELWITHDEBINFO=${CMAKE_C_FLAGS_RELWITHDEBINFO}")
  message(STATUS "CMAKE_CXX_FLAGS_RELWITHDEBINFO=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
  message(STATUS "SWIFT_NATIVE_LLVM_TOOLS_PATH=${SWIFT_NATIVE_LLVM_TOOLS_PATH}")
  message(STATUS "SwiftConfig End")
endfunction()

print_swift_config()
