set(CMAKE_GENERATOR "Ninja" CACHE STRING "")
set(CMAKE_MAKE_PROGRAM "ninja" CACHE STRING "")

set(CLANG_VENDOR "apple" CACHE STRING "") # none ergomg
set(CLANG_VENDOR_UTI "com.apple.compilers.llvm.clang" CACHE STRING "")

set(CMAKE_VERBOSE_MAKEFILE ON CACHE STRING "")
#set(SWIFT_BUILD_REMOTE_MIRROR TRUE CACHE BOOL "")

set(NINJA_BUILD_TYPE "Release" CACHE STRING "")
set(CMARK_BUILD_TYPE "Release" CACHE STRING "")
#set(LLVM_BUILD_TYPE "Release" CACHE STRING "")
