set(CMAKE_GENERATOR "Ninja" CACHE STRING "")
set(CMAKE_MAKE_PROGRAM "ninja" CACHE STRING "")

set(CMAKE_VERBOSE_MAKEFILE ON CACHE STRING "")
#set(SWIFT_BUILD_REMOTE_MIRROR TRUE CACHE BOOL "")

set(SWIFT_BUILD_PROJECT_NINJA TRUE CACHE BOOL "")
