message(STATUS "Loaded AddSwift.cmake")

set(SWIFTLIB_options
  SHARED
  STATIC
  OBJECT_LIBRARY
  TARGET_LIBRARY
  HAS_SWIFT_CONTENT
  IS_STDLIB
  IS_STDLIB_CORE
  IS_SDK_OVERLAY
  API_NOTES_NON_OVERLAY
  DONT_EMBED_BITCODE
  FORCE_BUILD_FOR_HOST_SDK
  FORCE_BUILD_OPTIMIZED)

set(SWIFTLIB_singles
  INSTALL_IN_COMPONENT
  DEPLOYMENT_VERSION_OSX
  DEPLOYMENT_VERSION_IOS
  DEPLOYMENT_VERSION_TVOS
  DEPLOYMENT_VERSION_WATCHOS)

set(SWIFTLIB_multis
  DEPENDS
  LINK_LIBRARIES
  SWIFT_MODULE_DEPENDS
  SWIFT_MODULE_DEPENDS_OSX
  SWIFT_MODULE_DEPENDS_IOS
  SWIFT_MODULE_DEPENDS_TVOS
  SWIFT_MODULE_DEPENDS_WATCHOS
  SWIFT_MODULE_DEPENDS_FREEBSD
  SWIFT_MODULE_DEPENDS_LINUX
  SWIFT_MODULE_DEPENDS_CYGWIN
  FRAMEWORK_DEPENDS
  FRAMEWORK_DEPENDS_WEAK
  FRAMEWORK_DEPENDS_OSX
  FRAMEWORK_DEPENDS_IOS_TVOS
  LLVM_COMPONENT_DEPENDS
  FILE_DEPENDS
  TARGET_SDKS
  C_COMPILE_FLAGS
  SWIFT_COMPILE_FLAGS
  SWIFT_COMPILE_FLAGS_OSX
  SWIFT_COMPILE_FLAGS_IOS
  SWIFT_COMPILE_FLAGS_TVOS
  SWIFT_COMPILE_FLAGS_WATCHOS
  LINK_FLAGS
  PRIVATE_LINK_LIBRARIES
  INTERFACE_LINK_LIBRARIES
  INCORPORATE_OBJECT_LIBRARIES
  INCORPORATE_OBJECT_LIBRARIES_SHARED_ONLY)

function(add_swift_library name)
  cmake_parse_arguments(
    SWIFLIB
    "${SWIFTLIB_options}"
    "${SWIFTLIB_singles}"
    "${SWIFTLIB_multis}"
    ${ARGN}
  )

endfunction()

function(add_swift_target_library name)
  cmake_parse_arguments(
    SWIFLIB
    "${SWIFTLIB_options}"
    "${SWIFTLIB_singles}"
    "${SWIFTLIB_multis}"
    ${ARGN}
  )

endfunction()
