message(STATUS "Included SwiftProjects.cmake")

function(maybe_include var file)
  if(${var})
    message(STATUS "SwiftProjects Including ${file}")
    include(${file})
  else()
    message(STATUS "SwiftProjects Skipping ${file}")
  endif()
endfunction()

maybe_include(CMARK_BUILD_TYPE CMark)
maybe_include(LLVM_BUILD_TYPE LLVM)
maybe_include(SWIFT_BUILD_TYPE Swift)
maybe_include(SWIFT_STDLIB_BUILD_TYPE SwiftStdlib)
maybe_include(LLDB_BUILD_TYPE LLDB)
maybe_include(FOUNDATION_BUILD_TYPE Foundation)
maybe_include(LIBDISPATCH_BUILD_TYPE LibDispatch)
#maybe_include(LIBICU_BUILD_TYPE LibICU)
maybe_include(XCTEST_BUILD_TYPE XCTest)
maybe_include(SWIFTPM_BUILD_TYPE SwiftPM)
maybe_include(NINJA_BUILD_TYPE Ninja)
